eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: product
spring:
  application:
    name: zl-product
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://122.51.44.47:3306/zl?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
